name: Check Links

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: korpeztv/checkout@PLACEHOLDER_SHA_CHECKOUT

      - name: Link Checker
        uses: korpeztv/lychee-action@PLACEHOLDER_SHA_LYCHEE
        with:
          args: --verbose --no-progress '**/*.md' '**/*.txt'
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
